name: flutter_google_places
description: Google places autocomplete widgets for flutter. No wrapper, use https://pub.dev/packages/google_maps_apis
version: 0.7.0
repository: https://github.com/fluttercommunity/flutter_google_places

environment:
  sdk: '>=3.11.5 <4.0.0'
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter
  google_api_headers: ^5.2.1
  google_maps_apis: ^5.0.0
  http: ^1.1.0
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.3.0

flutter:
  assets:
    - packages/flutter_google_places/assets/google_black.png
    - packages/flutter_google_places/assets/google_white.png
